server:
  port: 9101
  servlet:
    context-path: /api-backend
spring:
  cloud:
    nacos:
      config:
        namespace: ee7675c4-d2cc-48ab-8c8f-bd4461099886
        server-addr: @nacos-server-addr@
        file-extension: yaml
      discovery:
        namespace: ee7675c4-d2cc-48ab-8c8f-bd4461099886
        server-addr: @nacos-server-addr@
  config:
    import:
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  data:
    redis:
      host: localhost
      port: 30602
      database: 0
      lettuce:
        pool:
          max-idle: 16
          max-active: 32
          min-idle: 8
minio:
  endpoint: http://localhost:30606
  accessKey: re-minio
  secretKey: re#minio2022
  bucketName: re
