spring:
  application:
    name: api-backend
  profiles:
    active: @profiles.active@
  main:
    allow-circular-references: true
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 600000
