server:
  port: 9100
spring:
  cloud:
    nacos:
      config:
        namespace: ee7675c4-d2cc-48ab-8c8f-bd4461099886
        server-addr: @nacos-server-addr@
        file-extension: yaml
      discovery:
        namespace: ee7675c4-d2cc-48ab-8c8f-bd4461099886
        server-addr: @nacos-server-addr@
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders: "Content-Disposition,Content-Type,Cache-Control"
      routes:
        - id: re-auth
          uri: lb://re-auth
          predicates:
            - Path=/re-auth/**
        - id: re-service-sys-server
          uri: lb://re-service-sys-server
          predicates:
            - Path=/sys/**
        - id: api-backend
          uri: lb://api-backend
          predicates:
            - Path=/api-backend/**
  config:
    import:
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
