version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: re-mysql
    ports:
      - "30601:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 're#mysql2022'
      TZ: Asia/Shanghai
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    networks:
      - re-network
    restart: always

  redis:
    image: redis:8.4
    container_name: re-redis
    ports:
      - "30602:6379"
    command: redis-server --appendonly yes
    networks:
      - re-network
    restart: always

  nacos:
    image: nacos/nacos-server:v3.1.1
    container_name: re-nacos
    ports:
      - "30603:8848"
      - "31603:9848"
      - "30605:8080"
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_IDENTITY_KEY=re-nacos
      - NACOS_AUTH_IDENTITY_VALUE=re-nacos
      # re#nacos2022 base64 6 times
      - NACOS_AUTH_TOKEN=VmpGU1NtVkdXblJTYmxKVVlteEtWRmxzYUVOalJsSlZVVmhvVDFac1NsZFdWM1IzWWtaV1ZVMUVhejA9
    networks:
      - re-network
    restart: always

  minio:
    image: minio/minio:latest
    container_name: re-minio
    ports:
      - "30606:9000"
      - "30607:9001"
    environment:
      - MINIO_ROOT_USER=re-minio
      - MINIO_ROOT_PASSWORD=re#minio2022
      - TZ=Asia/Shanghai
    command: server /data --console-address ":9001"
    networks:
      - re-network
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: re-elasticsearch
    ports:
      - "30608:9200"
      - "30609:9300"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - TZ=Asia/Shanghai
    networks:
      - re-network
    restart: always

networks:
  re-network:
    driver: bridge
